// 값을 올리면 안정성/지연이 증가하는 항목은 아래에 따로 표시한다.
export const RECENT_FREQ_SIZE = 5; // 중앙값 창: 커질수록 안정적이나 느려진다.
export const NOTE_LOCK_COUNT = 3; // 노트 전환 확인 횟수.
export const STRING_LOCK_COUNT = 3; // 현 전환 확인 횟수.
export const IN_TUNE_CENTS = 5; // 성공 판정 진입 오차.
export const OUT_OF_TUNE_RELEASE_CENTS = 8; // 진입보다 넓게 유지해 경계 깜빡임을 방지한다.
export const NEAR_CENTS = 15; // 가까운 음정 표시 범위.
export const IN_TUNE_HOLD_MS = 500; // 순간 일치를 성공으로 오인하지 않도록 유지한다.
export const TONE_RESUME_DELAY_MS = 300; // 스피커 잔향이 사라진 뒤 분석 재개.
export const BEEP_IGNORE_MS = 180; // 확인음 80ms와 잔향 100ms.
export const WAKE_STATUS_MS = 3000;
export const HIDDEN_STOP_MS = 10000; // 숨김 10초 뒤 마이크 해제.
export const CONTEXT_RESUME_MS = 300;
export const STORAGE_KEY = 'tunestring-settings-v2';
export const LEGACY_STORAGE_KEY = 'tunestring-settings-v1';
export const CUSTOM_STORAGE_KEY = 'tunestring-custom-tunings-v1';
export const BUFFER_SIZE = 4096;
export const LOW_RANGE_BUFFER_SIZE = 8192;
export const RMS_MIN = 0.008; // 높이면 소음을 덜 받지만 약한 소리도 놓친다.
export const RMS_LEVELS = Object.freeze({ low: 0.014, normal: RMS_MIN, high: 0.004 });
export const MIN_FREQ = 25;
export const MAX_FREQ = 1100;
export const CLARITY_MIN = 0.9; // 높이면 불명료한 입력을 더 엄격히 거른다.
export const PEAK_RATIO = 0.9; // 강한 배음에서 기음의 첫 유효 피크를 선택한다.
export const ANALYSIS_INTERVAL_MS = 25;
export const EDGE_TOLERANCE_CENTS = 0.05; // 경계의 포물선 보간 오차만 흡수한다.
export const LOW_RANGE_THRESHOLD_HZ = 65;
export const GAUGE_MAX_CENTS = 50;
export const GAUGE_MAX_ANGLE = 90; // 반원 눈금의 양 끝점에 바늘이 닿는다.
export const GAUGE_SMOOTHING_MS = 43;
export const SILENCE_DEBOUNCE_MS = 600;
export const REJECT_DEBOUNCE_MS = 400;
export const SR_UPDATE_MS = 1000;
export const TRACE_SIZE = 120;
export const TRACE_DURATION_MS = 3000;
export const LONG_PRESS_MS = 500;
export const COMPLETE_BANNER_MS = 6000;
